name: hospital_app_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- CẦN PHẢI THÊM 2 DÒNG NÀY ---
  flutter_localizations:
    sdk: flutter
  # --- KẾT THÚC THÊM ---

  provider: ^6.1.2
  go_router: ^14.1.4
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  intl: ^0.20.2 # Phiên bản này đã đúng
  shared_preferences: ^2.2.3
  socket_io_client: ^2.0.3
  http: ^1.2.1
  jwt_decode: ^0.3.1
  json_annotation: ^4.9.0
  path: ^1.8.3
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  generate: true
